name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: "freebsd"
          os_version: "14.4"
          rust_version: "1.82.0"
        - os: "netbsd"
          os_version: "10.1"
          rust_version: "stable"
        - os: "openbsd"
          os_version: "7.8"
          rust_version: "stable"
        - os: "freebsd"
          freebsd_version: "15.0"
          rust_version: "nightly"
    name: ${{ matrix.os }} ${{ matrix.freebsd_version }} ${{ matrix.rust_version }}
    steps:
    - uses: actions/checkout@v6

    - name: Start VM
      if: matrix.os == 'freebsd'
      uses: vmactions/freebsd-vm@v1
      with:
        release: ${{ matrix.os_version }}
        usesh: true
        custom-shell-name: vmsh

    - name: Start VM
      if: matrix.os == 'netbsd'
      uses: vmactions/netbsd-vm@v1
      with:
        release: ${{ matrix.os_version }}
        usesh: true
        custom-shell-name: vmsh

    - name: Start VM
      if: matrix.os == 'openbsd'
      uses: vmactions/openbsd-vm@v1
      with:
        release: ${{ matrix.os_version }}
        usesh: true
        custom-shell-name: vmsh

    - name: Install dependencies
      if: matrix.os == 'freebsd'
      shell: vmsh {0}
      run: |
        pkg install -y curl
        fetch https://sh.rustup.rs -o rustup.sh
        sh rustup.sh -y --profile=minimal --default-toolchain ${{ matrix.rust_version }}
    - name: Install dependencies
      if: matrix.os == 'netbsd'
      shell: vmsh {0}
      run: |
        pkg_add curl
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install dependencies
      if: matrix.os == 'openbsd'
      shell: vmsh {0}
      run: |
        pkg_add rust

    - name: Build
      shell: vmsh {0}
      run: |
        if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
        cargo build
    - name: Test
      if: matrix.rust_version != '1.82.0'
      shell: vmsh {0}
      run: |
        if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
        df -h
        mount
        cargo test
    - name: Clippy
      if: matrix.rust_version == 'nightly'
      shell: vmsh {0}
      run: |
        if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
        rustup component add clippy
        cargo clippy --all-targets -- -D warnings
    - name: Fmt
      if: matrix.rust_version == 'nightly' && matrix.os == 'freebsd'
      shell: vmsh {0}
      run: |
        if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
        rustup component add rustfmt
        cargo fmt -- --check --color=never
    - name: Audit
      if: matrix.rust_version == 'nightly' && matrix.os == 'freebsd'
      shell: vmsh {0}
      run: |
        if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
        pkg install -y cargo-audit
        cargo audit
    - name: Minver
      if: matrix.rust_version == 'nightly' && matrix.os == 'freebsd'
      shell: vmsh {0}
      run: |
        if [ -f $HOME/.cargo/env ]; then . $HOME/.cargo/env; fi
        cargo update -Zdirect-minimal-versions
        cargo check --all-targets

  test-linux:
    runs-on: ubuntu-latest
    name: Linux nightly
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt
    - name: Run tests
      run: |
        cargo build
        cargo test
    - name: Clippy
      run: |
        cargo clippy --all-targets -- -D warnings
    - name: Fmt
      run: |
        cargo fmt -- --check --color=never
